### ISSUE TITLE
output path

### ISSUE THREAD

**Issue by SebSept** [Kaudaj/prestashop-maker#2]
**Is your feature request related to a problem? Please describe.**
when running `bin/console make-to <destination-path> <make-command>`
`./bin/console make-to /home/http/perso/prestashop/modules/vueseclatees/src/src/Command make:command`
I was expecting for the output file to be at `home/http/perso/prestashop/modules/vueseclatees/src/src/Command` but it's on 
`home/http/perso/prestashop/modules/vueseclatees/src/src/Command/src/Command/BackgroundScrappingCommand.php`

This means, I should write `./bin/console make-to /home/http/perso/prestashop/modules/vueseclatees/src/ make:command`

**Describe the solution you'd like**
just the inforamtion on the doc :D

**Comment by Kaudaj** [comment]
Ah yep exactly! You have to enter the project destination path. Entering the very final destination of the file is not conceivable to me since most of Symfony make commands (and the make commands I'll add in the future) alter/create multiple files in different locations. User can still arrange files afterwards as he wants to. 
By the way, it's better to use this tool when the destination project is under version control so you can see/revert the changes that have occurred.
Anyway: indeed, everything will be clearer with the README... 😅

**Comment by SebSept** [comment]
yep, nice explanation.

**Comment by Kaudaj** [comment]
Should now be clearer with the new README!

**Comment by tom-combet** [comment]
I consider it as done.

Feel free to re-open it if you think it can be improved!
